// <auto-generated />
namespace FogBugzPd.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FB2654_ChangeQaEstimateCustomFieldname_To_QaEstimateCustomFieldName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FB2654_ChangeQaEstimateCustomFieldname_To_QaEstimateCustomFieldName));
        
        string IMigrationMetadata.Id
        {
            get { return "201307311309585_FB2654_ChangeQaEstimateCustomFieldname_To_QaEstimateCustomFieldName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
