// <auto-generated />
namespace FogBugzPd.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDailyEmailsToFbAccountSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDailyEmailsToFbAccountSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201311071753024_AddDailyEmailsToFbAccountSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
