// <auto-generated />
namespace FogBugzPd.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FB2573_AllowQaEstimates_QaEstimateCustomFieldname2FbAccountSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FB2573_AllowQaEstimates_QaEstimateCustomFieldname2FbAccountSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201307091714110_FB2573_AllowQaEstimates_QaEstimateCustomFieldname2FbAccountSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
