// <auto-generated />
namespace FogBugzPd.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DailyDigestEmailGuidRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DailyDigestEmailGuidRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201311211917132_DailyDigestEmailGuidRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
