// <auto-generated />
namespace FogBugzPd.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FB2564_Rename_TestRailConfigId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FB2564_Rename_TestRailConfigId));
        
        string IMigrationMetadata.Id
        {
            get { return "201307101951194_FB2564_Rename_TestRailConfigId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
